// Lightweight test endpoint to send a one-off test email via Brevo (SendinBlue).
// Safety: requires TEST_EMAIL_TOKEN env var and request token (query `token` or header `x-test-token`).
// Usage: GET /api/test-email?token=xxx

const SibApiV3Sdk = require('sib-api-v3-sdk');

const submit = require('./submit');
const generateDocument = submit.generateDocument;

module.exports = async (req, res) => {
  // Read envs at request time so tests can mutate process.env between requires
  const TEST_TOKEN = process.env.TEST_EMAIL_TOKEN;
  const RECIPIENT = process.env.TEST_RECIPIENT_EMAIL || process.env.RECIPIENT_EMAIL;
  const SENDER = process.env.SENDER_EMAIL;
  const API_KEY = process.env.SENDINBLUE_API_KEY;

  // Allow GET for convenience
  const token = (req.query && req.query.token) || req.headers['x-test-token'];

  if (!TEST_TOKEN) {
    res.statusCode = 403;
    res.setHeader('Content-Type', 'application/json');
    res.end(
      JSON.stringify({
        success: false,
        message: 'TEST_EMAIL_TOKEN is not configured on the server.',
      })
    );
    return;
  }

  if (!token || token !== TEST_TOKEN) {
    res.statusCode = 401;
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify({ success: false, message: 'Invalid or missing token.' }));
    return;
  }

  if (!API_KEY || !SENDER || !RECIPIENT) {
    const missing = [];
    if (!API_KEY) missing.push('SENDINBLUE_API_KEY');
    if (!SENDER) missing.push('SENDER_EMAIL');
    if (!RECIPIENT) missing.push('RECIPIENT_EMAIL or TEST_RECIPIENT_EMAIL');
    res.statusCode = 500;
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify({ success: false, message: 'Missing required env vars', missing }));
    return;
  }

  try {
    // Build sample payload
    const sample = {
      FullName: 'Test User',
      FirstName_Arabic: 'اختبار',
      ContactInformation: 'This is a test submission generated by /api/test-email endpoint.',
    };

    // Generate DOCX buffer
    const docBuffer = await generateDocument(sample, { includeHeaderImage: false });
    const base64Docx = docBuffer.toString('base64');

    // Initialize Brevo
    let defaultClient = SibApiV3Sdk.ApiClient.instance;
    let apiKey = defaultClient.authentications['api-key'];
    apiKey.apiKey = API_KEY;
    let apiInstance = new SibApiV3Sdk.TransactionalEmailsApi();

    const sendSmtpEmail = new SibApiV3Sdk.SendSmtpEmail();
    sendSmtpEmail.subject = 'DS-160 Test Email (from api/test-email)';
    sendSmtpEmail.htmlContent = '<p>This is an automated test email with DOCX attachment.</p>';
    sendSmtpEmail.sender = { name: 'DS-160 Test', email: SENDER };
    sendSmtpEmail.to = [{ email: RECIPIENT }];
    sendSmtpEmail.attachment = [
      {
        content: base64Docx,
        name: `DS-160_Test_${Date.now()}.docx`,
        filename: `DS-160_Test_${Date.now()}.docx`,
        contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      },
    ];

    // Allow test/CI to skip the real network call by setting SKIP_SEND=true or running under NODE_ENV=test
    if (process.env.SKIP_SEND === 'true' || process.env.NODE_ENV === 'test') {
      console.log('SKIP_SEND is set; skipping real send and returning success (test mode).');
    } else {
      await apiInstance.sendTransacEmail(sendSmtpEmail);
    }

    res.statusCode = 200;
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify({ success: true, message: 'Test email sent (check recipient inbox).' }));
  } catch (err) {
    console.error('test-email error:', err);
    res.statusCode = 500;
    res.setHeader('Content-Type', 'application/json');
    res.end(
      JSON.stringify({
        success: false,
        message: 'Failed to send test email. See server logs for details.',
      })
    );
  }
};
